name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 0.17.4

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin
      web:
        pluginClass: AudioplayersPlugin
        fileName: audioplayers_web.dart

dependencies:
  uuid: ^3.0.1
  path_provider: ^2.0.1
  http: ^0.13.0
  test: ^1.16.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.22.0'

